Catkin-ProjectName: swig-wx
Version: 1.3.29

Depends: []

Description: This is a special version of swig needed by wxPython,
    which is SWIG version 1.3.29 plus some custom patches
    (explained at http://wxpython.org/builddoc.php).
    The patched latest version of wxPython SWIG is available at
    http://wxpython.wxcommunity.com/tools/

Author: http://www.swig.org
Maintainer: Dirk Thomas <dthomas@willowgarage.com>
Homepage: http://www.swig.org

Catkin-CopyrightType: willowgarage
Catkin-DebRulesType: +catkin/rules.em
